#!/bin/sh
[ -f "$HOME/.local/share/zap/zap.zsh" ] && source "$HOME/.local/share/zap/zap.zsh"

# completion
autoload -Uz bashcompinit && bashcompinit
autoload -Uz compinit
compinit

# history
HISTFILE=~/.zsh_history

# source
plug "$HOME/.config/zsh/aliases.zsh"
plug "$HOME/.config/zsh/exports.zsh"

# plugins
plug "esc/conda-zsh-completion"
# Suggest commands based on history
plug "zsh-users/zsh-autosuggestions"
# A simple plugin that auto-closes, deletes and skips over matching delimiters in zsh intelligently. Hopefully.
plug "hlissner/zsh-autopair"
# Menu autocompletion
plug "zap-zsh/supercharge"
#plug "zap-zsh/vim"
#plug "zap-zsh/zap-prompt"
# Init fzf completions and keybinds 
plug "zap-zsh/fzf"
# Replaces ls with exa
plug "zap-zsh/exa"
# Fish-like syntax highlighting
plug "zsh-users/zsh-syntax-highlighting"
# Replace zsh's default completion selection menu with fzf!
plug "aloxaf/fzf-tab"
#plug "freed-wu/fzf-tab-source"
plug "timoohara/zsh-aws"
# Load after zsh-autosuggestions and zsh-syntax-highlighting
# Friendly bindings for zsh's vi mode
plug "softmoth/zsh-vim-mode"

# keybinds
bindkey '^ ' autosuggest-accept
bindkey -M viins '^R' fzf-history-widget 
bindkey -M vicmd '?' fzf-history-widget 
bindkey -M vicmd '/' fzf-history-widget 

# Note: fzf-tab tends to negate the effect of these
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char

export PATH="$HOME/.local/bin":$PATH

if command -v bat &> /dev/null; then
  alias cat="bat -pp --theme \"Visual Studio Dark+\"" 
  alias catt="bat --theme \"Visual Studio Dark+\"" 
fi

eval "$(starship init zsh)"
export STARSHIP_CONFIG=~/.config/starship/starship.toml
source ~/.env.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/completion.zsh.inc"; fi

# bun completions
[ -s "/Users/timothyohara/.bun/_bun" ] && source "/Users/timothyohara/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
